name: Java CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        java-version: ['11','16','17']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{matrix.java-version}}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
